type Employee {
    id: Int
    name: String
    designation: String
    address: String
    status: Int
    hobbies: [String]//String
}

type Query {
    employees: [Employee]
        @resolver(class: "Adobe\\Employee\\Model\\Resolver\\Employees")
}

type Mutation {
    createEmployee(
        name: String!
        designation: String
        address: String
        status: Int
        hobbies: [String]
    ): Employee
        @resolver(class: "Adobe\\Employee\\Model\\Resolver\\CreateEmployee")

    updateEmployee(
        id: Int!
        name: String
        designation: String
        address: String
        status: Int
        hobbies: [String]
    ): Employee
        @resolver(class: "Adobe\\Employee\\Model\\Resolver\\UpdateEmployee")

    deleteEmployee(
        id: Int!
    ): Boolean
        @resolver(class: "Adobe\\Employee\\Model\\Resolver\\DeleteEmployee")
}